### Get all players
GET http://localhost:3000/api/players

### Get player by id
GET http://localhost:3000/api/players/1

### Create new player
POST http://localhost:3000/api/players
Content-Type: application/json

{
    "name": "John Doe",
    "jersey": 10
}

### Update player
PUT http://localhost:3000/api/players/1
Content-Type: application/json

{
    "name": "John Doe Updated",
    "jersey": 11
}   

### Delete player
DELETE http://localhost:3000/api/players/1
